title: Arrow
#-------------------------
name: Λrrow
#-------------------------
description: Functional companion to Kotlin's Standard Library
#-------------------------
author: The Λrrow Authors
keywords: functional-programming, kotlin-library, monads, monad-transformers, functional-data-structure, kotlin, fp-types, adt, free-monads, tagless-final, mtl, for-comprehension, category-theory
#-------------------------
url: https://arrow-kt.io
#-------------------------
github_repo: https://github.com/arrow-kt/arrow
#-------------------------
twitter_handle: "@arrow_kt"
#-------------------------
slack_kotlin_channel: "https://slack.kotlinlang.org"
slack_arrow_channel: "https://kotlinlang.slack.com/archives/C5UPMM0A0"
#-------------------------
sass:
    style: compressed
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', '.bundle', 'apidocs/', 'docs/', 'css/docs-styles.scss', 'img/core/', 'img/docs/', 'img/fx/', 'img/incubator/', 'img/kotlin-stdlib.png', 'img/labels/', 'img/linting/', 'img/meta/', 'img/old-design/', 'img/optics/', 'img/quickstart/']
#-------------------------
collections:
  code:
    output: true
# Default Front Matter values to be set
defaults:
  - scope:
      type: code
    values:
      layout: code

# Plugins
plugins:
  - jekyll-redirect-from
