package arrow.ap.tests

import arrow.derive.DerivingProcessor

class DerivingTest : APTest("arrow.ap.objects", enforcePackage = false) {

  init {
    testProcessor(
      AnnotationProcessor(
        name = "Instances are generated by deriving annotation",
        sourceFiles = listOf("deriving/Deriving.java"),
        destFile = "deriving/Deriving2.kt",
        processor = DerivingProcessor()
      ),
      actualFileLocation = {
        "${it.path}/deriving"
      }
    )
  }
}