// Generated by raise-ktor-server.main.kts

package arrow.raise.ktor.server

import arrow.core.raise.RaiseDSL
import io.ktor.http.*
import io.ktor.server.routing.*
import io.ktor.utils.io.*
import kotlin.jvm.JvmName

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseTyped")
public inline fun <reified B : Any, reified R> Route.patchOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = patch<B> { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseTypedPath")
public inline fun <reified B : Any, reified R> Route.patchOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = patch<B>(path) { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseTypedRegex")
public inline fun <reified B : Any, reified R> Route.patchOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = patch<B>(path) { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseTyped")
public inline fun <reified B : Any, reified R> Route.postOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = post<B> { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseTypedPath")
public inline fun <reified B : Any, reified R> Route.postOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = post<B>(path) { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseTypedRegex")
public inline fun <reified B : Any, reified R> Route.postOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = post<B>(path) { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseTyped")
public inline fun <reified B : Any, reified R> Route.putOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = put<B> { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseTypedPath")
public inline fun <reified B : Any, reified R> Route.putOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = put<B>(path) { respondOrRaise(statusCode) { body(it) } }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseTypedRegex")
public inline fun <reified B : Any, reified R> Route.putOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: suspend RaiseRoutingContext.(B) -> R,
): Route = put<B>(path) { respondOrRaise(statusCode) { body(it) } }
