// Generated by raise-ktor-server.main.kts
@file:Suppress("API_NOT_AVAILABLE")

package arrow.raise.ktor.server.routing

import arrow.core.raise.RaiseDSL
import io.ktor.http.*
import io.ktor.server.routing.*
import io.ktor.utils.io.*
import kotlin.jvm.JvmName

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseTyped")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.patchOrRaise(
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = patch { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseTypedPath")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.patchOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = patch(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseTypedRegex")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.patchOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = patch(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseTyped")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.postOrRaise(
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = post { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseTypedPath")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.postOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = post(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseTypedRegex")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.postOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = post(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseTyped")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.putOrRaise(
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = put { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseTypedPath")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.putOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = put(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseTypedRegex")
@IgnorableReturnValue
public inline fun <reified TRequest : Any, reified TResponse> Route.putOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  body: ReceivingRespondingRaiseRoutingHandler<TRequest, TResponse>,
): Route = put(path) { respondOrRaise(statusCode, body) }
