// Generated by raise-ktor-server.main.kts
@file:Suppress("API_NOT_AVAILABLE")

package arrow.raise.ktor.server.routing

import arrow.core.raise.RaiseDSL
import io.ktor.http.*
import io.ktor.server.routing.*
import io.ktor.utils.io.*
import kotlin.jvm.JvmName

@KtorDsl
@RaiseDSL
@JvmName("deleteOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.deleteOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = delete { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("deleteOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.deleteOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = delete(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("deleteOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.deleteOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = delete(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("getOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.getOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = get { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("getOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.getOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = get(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("getOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.getOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = get(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("headOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.headOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = head { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("headOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.headOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = head(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("headOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.headOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = head(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("optionsOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.optionsOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = options { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("optionsOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.optionsOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = options(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("optionsOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.optionsOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = options(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.patchOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = patch { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.patchOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = patch(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("patchOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.patchOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = patch(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.postOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = post { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.postOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = post(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("postOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.postOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = post(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaise")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.putOrRaise(
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = put { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaisePath")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.putOrRaise(
  path: String,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = put(path) { respondOrRaise(statusCode, body) }

@KtorDsl
@RaiseDSL
@JvmName("putOrRaiseRegex")
@IgnorableReturnValue
public inline fun <reified TResponse> Route.putOrRaise(
  path: Regex,
  statusCode: HttpStatusCode? = null,
  crossinline body: RespondingRaiseRoutingHandler<TResponse>,
): Route = put(path) { respondOrRaise(statusCode, body) }
