name: "Build"

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - main

env:
  JAVA_OPTS: -Xms1g -Xmx3g
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  check:
    strategy:
      matrix:
        os: [ windows-latest, macos-11.0 ]
    runs-on: ${{matrix.os}}
    timeout-minutes: 30
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Restore Gradle cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
            ~/.konan
          key: ${{ runner.os }}-check-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-check-

      - name: Run Ubuntu tests
        if: matrix.os == 'macos-11.0'
        run: ./gradlew check

      - name: Run Windows tests
        if: matrix.os == 'windows-latest'
        run: ./gradlew mingwX64Test
