name: "kover"

on:
  pull_request_target:
    paths:
      - '**.kt'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Create code coverage report
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew koverMergedReport

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Kover Report
          update-comment: true

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.0
        with:
          name: 'kover-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Stop Gradle daemons
        run: ./gradlew --stop